import clsx from 'clsx'
import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import { madeTommy } from "@/lib/fonts";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper"; // ✅ Import wrapper


const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className={clsx('dark', mulish.variable, madeTommy.variable, 'antialiased')}>
        <SessionWrapper>
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
